baseURL = "https://intermezzio.github.io/JEFFRIS"
languageCode = "en-us"
publishDir = "docs"
title = "JEFFRIS"
themesDir = "themes/"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 3

[[menu.main]]
    name = "Pi"
    url = "/docs/pi/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/docs/about/"
    weight = 2


[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Learn More'
  homepage_intro = 'homepage_intro here'
  homepage_image = 'remsens-sky-kite.jpg'
  homepage_caption = 'Students in the Remote Sensing course fly kites (above) equipped with Raspberry Pis for aerial imaging'

  [params.homepage_meta_tags]
    meta_description = "JEFFRIS is a project for MIT Beaver Works Summer Institute Remote Sensing course, where aerial images from Raspberry Pis are processed using Python and OpenCV"
    meta_og_title = "JEFFRIS Home"
    meta_og_type = "website"
    meta_og_url = "https://intermezzio.github.io/JEFFRIS"
    meta_og_image = "mit-bwsi-full.png"
    meta_og_description = "JEFFRIS is a project for MIT Beaver Works Summer Institute Remote Sensing course, where aerial images from Raspberry Pis are processed using Python and OpenCV"

  [params.logo]
      mobile = "mit-bwsi.png"
      standard  = "mit-bwsi.png"
